---
title: "R Notebook"
output: html_notebook
---
Part 1 

```{r}
mymatrix <- matrix(seq(2,35, by = 3), 2, 6)
mymatrix
```

```{r}
library(nlme)
Gasoline
str(Gasoline)
?Gasoline
```
```{r}
mean(Gasoline['vapor'])
```

```{r}
residual = Gasoline['vapor'] - mean(Gasoline['vapor'])

residualsq = residual * residual
integral = sum(residualsq)

variance = 1/(length(Gasoline['vapor'] ) -1) * integral

variance
```

```{r}
varianceAuto = var(Gasoline['vapor'])
varianceAuto
```

```{r}
hist(Gasoline$yield, col = "red", xlab = "Gasoline Yield", ylab = "Count", main = "Histogram for Yield")
```

```{r}
summary(Gasoline['yield'])
```

```{r}

boxplot(Gasoline$endpoint~Gasoline$Sample, col=c("red","purple", "pink"), xlab="Sample", ylab="Distribution of endpoint", main = "Boxplot of endpoint and sample for Gasoline")
```
```{r}


plot(Gasoline$yield~Gasoline$endpoint, ylab="Yield", xlab="Distribution of endpoint", main = "Plot of endpoint and sample for Gasoline")
blah = lm(Gasoline$yield~Gasoline$endpoint)
abline(blah, col="red")
```

```{r}

```

```{r}

```

